// Shared, non-secret editor definitions. The Astro UI and admin service use these.
const field = (name, label, type = 'text', extra = {}) => ({ name, label, type, ...extra });
const title = field('title', 'Title');
const summary = field('summary', 'Summary', 'textarea');
const order = field('order', 'Display order', 'number');
const sample = field('placeholder', 'Sample content', 'boolean');
const draft = field('draft', 'Keep unpublished', 'boolean');
const curriculum = field('curriculum', 'Collection', 'select', { options: ['2028', 'grade-10', 'archive'] });
const refs = (name, label, collection) => field(name, label, 'references', { collection });
export const collections = {
  topics: { label: 'Study notes', singular: 'Study note', extension: 'mdx', fields: [title, field('shortTitle', 'Short pin label'), summary, field('unit', 'Syllabus unit', 'reference', { collection: 'syllabus' }), curriculum, field('level', 'Course level', 'select', { options: ['SL', 'HL'] }), field('period.start', 'Start year', 'number'), field('period.end', 'End year', 'number'), field('location.place', 'Place'), field('location.lat', 'Latitude', 'number'), field('location.lng', 'Longitude', 'number'), field('keyQuestions', 'Key questions (one per line)', 'lines'), refs('authors', 'Teachers', 'teachers'), refs('related', 'Related notes', 'topics'), field('updated', 'Updated', 'date'), draft], defaults: { title: 'Untitled study note', summary: '', unit: 'p1-political-economic-transitions', curriculum: '2028', level: 'SL', period: { start: 1789, end: 1789 }, location: { place: '', lat: 0, lng: 0 }, keyQuestions: [], authors: [], related: [], draft: true }, body: '## Overview\n\nWrite the context and analysis here.\n\n## Historians’ debate\n\nAttribute interpretations to real works.\n\n## Test yourself\n\n<Recall q="What changed, and why?">Add the answer.</Recall>\n' },
  glossary: { label: 'Glossary', singular: 'Key term', extension: 'md', fields: [field('term', 'Term'), field('definition', 'Definition', 'textarea'), field('significance', 'Significance', 'textarea'), field('when', 'Date or period'), refs('related', 'Related terms', 'glossary')], defaults: { term: 'Untitled term', definition: '', significance: '', related: [] }, body: '' },
  teachers: { label: 'Teachers', singular: 'Teacher profile', extension: 'md', fields: [field('name', 'Name'), field('role', 'Role'), field('email', 'Email', 'email'), refs('courses', 'Courses', 'courses'), field('education', 'Education (one per line)', 'lines'), field('interests', 'Interests (one per line)', 'lines'), field('quote', 'Teaching philosophy or attributed quotation', 'textarea'), order, sample], defaults: { name: 'New teacher', role: 'History teacher', courses: [], education: [], interests: [], order: 100, placeholder: true }, body: 'Add the teacher’s biography.\n' },
  courses: { label: 'Courses', singular: 'Course', extension: 'md', fields: [title, field('code', 'Course code'), field('grades', 'Grades'), field('level', 'Level'), summary, refs('units', 'Syllabus units', 'syllabus'), field('assessment', 'Assessment components', 'assessment'), order, sample], defaults: { title: 'New course', grades: '11–12', level: 'IB Diploma', summary: '', units: [], assessment: [], order: 100, placeholder: true }, body: 'Describe this course.\n' },
  news: { label: 'News', singular: 'News post', extension: 'md', fields: [title, field('date', 'Date', 'date'), summary, field('tags', 'Tags (one per line)', 'lines'), sample, draft], defaults: { title: 'New post', date: '', summary: '', tags: [], placeholder: false, draft: true }, body: 'Write the announcement here.\n' },
  guides: { label: 'Study guides', singular: 'Study guide', extension: 'mdx', fields: [title, field('category', 'Category', 'select', { options: ['Assessment', 'Skills', 'Research'] }), summary, order, field('updated', 'Updated', 'date')], defaults: { title: 'New guide', category: 'Skills', summary: '', order: 100 }, body: '## Overview\n\nWrite the guide here.\n' },
  syllabus: { label: 'Syllabus', singular: 'Syllabus unit', extension: 'md', fields: [title, curriculum, field('paper', 'Paper', 'number'), field('component', 'Component'), field('levels', 'Levels', 'select', { options: ['SL & HL', 'HL only'] }), field('description', 'Description', 'textarea'), order], defaults: { title: 'New unit', curriculum: '2028', paper: 1, component: '', levels: 'SL & HL', description: '', order: 100 }, body: '' },
  snapshots: { label: 'Timeline context', singular: 'Year context', extension: 'md', fields: [field('year', 'Year (negative for BCE)', 'number'), title, summary, field('highlights', 'Highlights (one per line)', 'lines')], defaults: { year: 1789, title: 'The world in 1789', summary: '', highlights: [], borderYear: null }, body: '' },
};
