import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, symlink, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createStore } from './store.mjs';
import { collections } from './collections.mjs';
const exec = promisify(execFile);
const run = async (cwd, ...args) => (await exec('git', ['-C', cwd, ...args], { windowsHide: true })).stdout.trim();
test('drafts persist, detect concurrent edits, validate before publishing and survive failures', { timeout: 60000 }, async (t) => {
  const root = await mkdtemp(join(tmpdir(), 'strhistory-admin-test-'));
  t.after(async () => { await rm(root, { recursive: true, force: true }); });
  const remote = join(root, 'remote'); const repo = join(root, 'authoring');
  await mkdir(remote); await run(remote, 'init', '--bare', '--initial-branch=main');
  await exec('git', ['clone', remote, repo], { windowsHide: true });
  await run(repo, 'config', 'user.email', 'test@example.invalid'); await run(repo, 'config', 'user.name', 'Editor test');
  await writeFile(join(repo, '.gitignore'), 'node_modules/\n.teacher-authoring\n');
  await writeFile(join(repo, 'package.json'), '{"type":"module"}');
  await symlink(join(process.cwd(), 'node_modules'), join(repo, 'node_modules'), process.platform === 'win32' ? 'junction' : 'dir');
  await writeFile(join(repo, '.teacher-authoring'), 'isolated test checkout');
  for (const collection of Object.keys(collections)) await mkdir(join(repo, 'src/content', collection), { recursive: true });
  const sourcePath = 'src/content/glossary/example.md';
  await writeFile(join(repo, sourcePath), '---\nterm: Example\ndefinition: Initial definition\nsignificance: Initial significance\nrelated: []\n---\n\n');
  await run(repo, 'add', '.'); await run(repo, 'commit', '-m', 'Fixture'); await run(repo, 'push', '-u', 'origin', 'main');
  const config = { repo, data: join(root, 'data') };
  let fail = false; let checks = 0;
  const runChecks = async () => { checks++; if (fail) throw new Error('Synthetic build failure'); };
  let store = await createStore(config, { runChecks });
  const original = await store.read('glossary', 'example');
  const saved = await store.save({ ...original, fields: { ...original.fields, definition: 'A revised definition' } });
  await assert.rejects(store.save({ ...original, body: 'Stale teacher edit' }), /Another teacher/);
  assert.match(await readFile(join(repo, sourcePath), 'utf8'), /Initial definition/);
  store = await createStore(config, { runChecks });
  assert.equal((await store.read('glossary', 'example')).fields.definition, 'A revised definition');
  const wait = async () => { for (let i = 0; store.busy && i < 400; i++) await new Promise((r) => setTimeout(r, 50)); assert.equal(store.busy, false); };
  fail = true; await store.publish('glossary', 'example', saved.draftVersion); await wait();
  assert.equal(store.status().phase, 'failed'); assert.match(store.status().detail, /Synthetic build failure/);
  assert.equal((await store.read('glossary', 'example')).hasDraft, true);
  assert.match(await run(remote, 'show', 'main:' + sourcePath), /Initial definition/);
  fail = false; await store.publish('glossary', 'example', saved.draftVersion); await wait();
  assert.equal(store.status().phase, 'published', store.status().detail); assert.ok(store.status().sha); assert.equal(checks, 2);
  assert.match(await run(remote, 'show', 'main:' + sourcePath), /A revised definition/);
  const published = await store.read('glossary', 'example'); assert.equal(published.hasDraft, false);
  const conflict = await store.save({ ...published, body: 'Teacher draft' });
  const other = join(root, 'other'); await exec('git', ['clone', remote, other], { windowsHide: true });
  await writeFile(join(other, sourcePath), '---\nterm: Example\ndefinition: Another contributor\nsignificance: New source\n---\n');
  await run(other, 'add', '.'); await run(other, '-c', 'user.name=Other', '-c', 'user.email=other@example.invalid', 'commit', '-m', 'Concurrent edit'); await run(other, 'push');
  await store.publish('glossary', 'example', conflict.draftVersion); await wait();
  assert.equal(store.status().phase, 'failed'); assert.match(store.status().detail, /published entry changed/);
  assert.match(await run(remote, 'show', 'main:' + sourcePath), /Another contributor/);
  assert.equal((await store.read('glossary', 'example')).changedUpstream, true);
  await assert.rejects(store.discard('glossary', 'example', 'wrong-version'), /changed/);
  await store.discard('glossary', 'example', conflict.draftVersion);
  assert.equal((await store.read('glossary', 'example')).hasDraft, false);
  const added = await store.save({ collection: 'glossary', slug: 'new-term', fields: { term: 'New term', definition: 'Definition', significance: 'Significance' }, body: '', revision: null, draftVersion: null });
  fail = true; await store.publish('glossary', 'new-term', added.draftVersion); await wait();
  assert.equal(store.status().phase, 'failed');
  await assert.rejects(readFile(join(repo, 'src/content/glossary/new-term.md')), { code: 'ENOENT' });
  fail = false; await store.publish('glossary', 'new-term', added.draftVersion); await wait();
  assert.equal(store.status().phase, 'published', store.status().detail);
  assert.match(await run(remote, 'show', 'main:src/content/glossary/new-term.md'), /New term/);
});
